### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by benjaminhobbs** [thibaudcolas/thibaudcolas#7]
There's a link in this repo, here:
https://github.com/thibaudcolas/thibaudcolas/blob/6c40b959508198593d86fdcbf2ab7cbb0be3201b/src/_posts/2019-06-05-accessibility-workshop-at-pixel-pioneers-2019.md

to
https://bbc-news.github.io/accessibility-news-and-you/
this has now moved to
https://bbc.github.io/accessibility-news-and-you/

**Comment by thibaudcolas** [comment]
Thanks @benjaminhobbs, should be fixed now 🙂
